server:
  port: 8080
  address: 0.0.0.0

spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:trailence}
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH_ENABLED}
          starttls:
            enable: ${SMTP_TLS_ENABLED}

trailence:
  jwt:
    secret: ${TRAILENCE_JWT_SECRET}
  hostname: ${TRAILENCE_HOSTNAME:trailence.org}
  protocol: ${TRAILENCE_PROTOCOL:https}
  linkpath: ${TRAILENCE_LINK_PATH:/link/}
  external:
    geonames:
      username: ${GEONAMES_USER:}
