server:
  port: 8080
  address: 0.0.0.0

spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:trailence}
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}
    pool:
      enabled: true
      max-size: 100
      initial-size: 3

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT:25}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH_ENABLED:true}
          starttls:
            enable: ${SMTP_TLS_ENABLED:true}

  codec:
    max-in-memory-size: 1MB

trailence:
  jwt:
    secret: ${TRAILENCE_JWT_SECRET}
    validity: ${TRAILENCE_JWT_VALIDITY:60m}
  hostname: ${TRAILENCE_HOSTNAME:trailence.org}
  protocol: ${TRAILENCE_PROTOCOL:https}
  linkpath: ${TRAILENCE_LINK_PATH:/link/}
  external:
    geonames:
      url: "http://api.geonames.org"
      username: ${GEONAMES_USER:}
    captcha:
      provider: ${CAPTCHA_PROVIDER:turnstile}
      clientKey: ${CAPTCHA_CLIENT_KEY:}
      secretKey: ${CAPTCHA_SECRET_KEY:}
    outdooractive:
      clientKey: ${OUTDOOR_ACTIVE_KEY:}
      userRole: ${OUTDOOR_ACTIVE_ROLE:}
    visorando:
      userRole: ${VISORANDO_ROLE:}
    kofi:
      verificationToken: ${KOFI_TOKEN:}
  storage:
    type: ${TRAILENCE_STORAGE_TYPE:fs}
    username: ${TRAILENCE_STORAGE_USERNAME:}
    password: ${TRAILENCE_STORAGE_PASSWORD:}
    root: ${TRAILENCE_STORAGE_ROOT:./storage-fs}
    url: ${TRAILENCE_STORAGE_URL:}
  free-plan:
    collections: ${FREE_PLAN_COLLECTIONS:10}
    trails: ${FREE_PLAN_TRAILS:1000}
    tracks: ${FREE_PLAN_TRACKS:2000}
    tracks_size: ${FREE_PLAN_TRACKS_SIZE:10485760}
    photos: ${FREE_PLAN_PHOTOS:500}
    photos_size: ${FREE_PLAN_PHOTOS_SIZE:104857600}
    tags: ${FREE_PLAN_TAGS:500}
    trail_tags: ${FREE_PLAN_TRAIL_TAGS:2000}
    shares: ${FREE_PLAN_SHARES:50}
  mail:
    from:
      email: ${TRAILENCE_MAIL_FROM_EMAIL:trailence@trailence.org}
      name: ${TRAILENCE_MAIL_FROM_NAME:Trailence}
    throttling:
      max: ${TRAILENCE_MAX_MAILS:500}
      max-delay: ${TRAILENCE_MAX_MAILS_DELAY:1d}
      min-delay: ${TRAILENCE_MAILS_MIN_DELAY:1m}
      min-delay-count: ${TRAILENCE_MAILS_MIN_DELAY_COUNT:10}
  translations:
    url: ${TRAILENCE_TRANSLATION_SERVICE_URL:}
  extensions:
    allowed:
      "[thunderforest.com]":
        enabled: ${THUNDERFOREST_ENABLED:false}
        role: ${THUNDERFOREST_ROLE:}
        content:
          apikey:
            pattern: "[0-9a-f]{32}" 
